version: '3.7'

networks:
  pydio:

services:
  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    ports: 
      - ${PYDIO_PORT}:8080
    environment:
      - CELLS_LOG_LEVEL=production
      - CELLS_BIND=${PUBLIC_URI}
    volumes:
      - cellsdir:/var/cells
      - data:/var/cells/data
    networks:
      - pydio

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - mysqldir:/var/lib/mysql
    networks:
      - pydio

volumes:
    data:
    cellsdir:
    mysqldir:
